# Check tensorflow installation

In [1]:
import tensorflow as tf

The usual hello world

In [2]:
a = tf.constant('Hello my friend')
# this should not print the contents of a
print "Before running the graph a is:"
print a

# Creates a session with log_device_placement set to True.
sess = tf.Session()
# Runs the op. (This should print the contents of a by running the graph)
print "\nBy running the graph as a:"
print(sess.run(a))


Before running the graph a is:
Tensor("Const:0", shape=(), dtype=string)

By running the graph as a:
Hello my friend


# Moving on
Lets try now with a graph involving more than one node

In [3]:
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 4.0, 2.0, 5.0, 3.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
print(sess.run(c))

[[ 14.  32.]
 [ 32.  77.]]


Add a placeholder and a variable to spice things up

In [4]:
d = tf.placeholder(tf.float32, name='d')
e = tf.Variable(tf.random_uniform([2, 2], -10.0, 10.0), name='e')

# Add an op to initialize the variables.
init_op = tf.global_variables_initializer()
# AND INITIALIZE THEM
sess.run(init_op)
# more fun 
f = tf.add(c, tf.multiply(d, e), name='f')
import numpy as np
# A little assignment to the value of d to compute f
print(sess.run(f, {d: np.ones((2,2))}))


[[ 19.85029602  23.33823586]
 [ 40.75460815  78.15203094]]


# TensorBoard visualization
Let's take a look at what we've got so far

In [5]:
file_writer = tf.summary.FileWriter('./the_graph', sess.graph)


run in a terminal:
```bash
python -m tensorflow.tensorboard --logdir=./the_graph/
```
to start the tensorboard and open http://0.0.0.0:6006/ on a browser to display it

In [6]:
g = tf.add(c, e, name='g')
file_writer.flush()
print(sess.run(g))

[[ 19.85029602  23.33823586]
 [ 40.75460815  78.15203094]]


That's all folks!